# Generated by Django 5.0.4 on 2024-05-04 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_bufferlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='bufferlist',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bufferlist',
            name='desire',
            field=models.BooleanField(default=False),
        ),
    ]
