# Generated by Django 5.0.4 on 2024-05-04 04:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_bufferlist_comment_bufferlist_desire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bufferlist',
            name='place',
        ),
        migrations.AddField(
            model_name='bufferlist',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
