# Generated by Django 5.0.4 on 2024-05-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='file_url',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.TextField(),
        ),
    ]
