# Generated by Django 5.0.4 on 2024-05-18 09:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_event_file_url_alter_event_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='time_date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
