# Generated by Django 5.0.4 on 2024-05-18 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_rename_time_date_event_start_date_event_end_date'),
        ('user', '0002_remove_user_email_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='leader_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
