# Generated by Django 5.0.4 on 2024-05-12 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, default=None, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
